In [2]:
import pandas as pd

In [3]:
df2 = pd.read_csv('Data02.csv')
print(df2.shape)
df2.head()

(46749, 9)

,결제수단,배송번호,배송시작일,배송완료일,상품구매금액,상품번호,수량,주문경로,주문일
0,무통장입금,D-20181227-0000648-00,2019-01-07 오전 8:56,2019-01-11 오전 5:32,71450,1077.0,1,PC쇼핑몰,20181227
1,무통장입금,D-20181229-0000119-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,141240,42.0,2,모바일웹,20181229
2,무통장입금,D-20181230-0000100-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,13910,1271.0,1,모바일웹,20181230
3,무통장입금,D-20181231-0000087-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,81600,1085.0,1,모바일웹,20181231
4,무통장입금,D-20181231-0000108-00,2019-01-07 오전 8:56,2019-01-11 오전 5:32,94710,1106.0,1,모바일웹,20181231

In [6]:
df2['배송시작일']   # dtype: object 문자로 인식

0         2019-01-07 오전 8:56
1         2019-01-03 오전 9:30
2         2019-01-03 오전 9:30
3         2019-01-03 오전 9:30
4         2019-01-07 오전 8:56
                ...
46744     2017-12-29 오후 4:32
46745     2018-01-03 오전 9:45
46746     2018-01-02 오후 7:06
46747     2018-01-03 오후 2:00
46748    2018-01-03 오후 12:43
Name: 배송시작일, Length: 46749, dtype: object

In [ ]:
pd.to_datetime(df2['배송시작일'])   # TypeError : to_datetime으로 처리할수 있는 데이터 형태가 있다.

In [13]:
df2['배송시작일']   # 앞에 있는 2019-01-07 만 빼오자

0         2019-01-07 오전 8:56
1         2019-01-03 오전 9:30
2         2019-01-03 오전 9:30
3         2019-01-03 오전 9:30
4         2019-01-07 오전 8:56
                ...
46744     2017-12-29 오후 4:32
46745     2018-01-03 오전 9:45
46746     2018-01-02 오후 7:06
46747     2018-01-03 오후 2:00
46748    2018-01-03 오후 12:43
Name: 배송시작일, Length: 46749, dtype: object

In [11]:
def date_function(x):
    return x[0:10]

df2['배송시작일'].apply(date_function)  # df2['배송시작일'] 의 데이터 시리즈가 한줄한줄 date_function함수의 인자에 들어감

0        2019-01-07
1        2019-01-03
2        2019-01-03
3        2019-01-03
4        2019-01-07
            ...
46744    2017-12-29
46745    2018-01-03
46746    2018-01-02
46747    2018-01-03
46748    2018-01-03
Name: 배송시작일, Length: 46749, dtype: object

In [15]:
pd.to_datetime(df2['배송시작일'].apply(date_function))  # dtype: datetime64[ns]
df2['배송시작일(datetime)'] = pd.to_datetime(df2['배송시작일'].apply(date_function))

In [17]:
df2['배송완료일(datetime)'] = pd.to_datetime(df2['배송완료일'].apply(date_function))
df2

,결제수단,배송번호,배송시작일,배송완료일,상품구매금액,상품번호,수량,주문경로,주문일,배송시작일(datetime),배송완료일(datetime)
0,무통장입금,D-20181227-0000648-00,2019-01-07 오전 8:56,2019-01-11 오전 5:32,71450,1077.0,1,PC쇼핑몰,20181227,2019-01-07,2019-01-11
1,무통장입금,D-20181229-0000119-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,141240,42.0,2,모바일웹,20181229,2019-01-03,2019-01-07
2,무통장입금,D-20181230-0000100-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,13910,1271.0,1,모바일웹,20181230,2019-01-03,2019-01-07
3,무통장입금,D-20181231-0000087-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,81600,1085.0,1,모바일웹,20181231,2019-01-03,2019-01-07
4,무통장입금,D-20181231-0000108-00,2019-01-07 오전 8:56,2019-01-11 오전 5:32,94710,1106.0,1,모바일웹,20181231,2019-01-07,2019-01-11
...,...,...,...,...,...,...,...,...,...,...,...
46744,카드,D-20171229-0000036-00,2017-12-29 오후 4:32,2018-01-02 오전 5:31,52800,445.0,1,모바일웹,20171229,2017-12-29,2018-01-02
46745,카드,D-20171229-0000043-00,2018-01-03 오전 9:45,2018-01-07 오전 5:38,112200,172.0,2,모바일웹,20171229,2018-01-03,2018-01-07
46746,카드,D-20171230-0000022-01,2018-01-02 오후 7:06,2018-01-11 오전 2:46,36000,140.0,1,네이버 페이,20171230,2018-01-02,2018-01-11
46747,카드,D-20171231-0000017-01,2018-01-03 오후 2:00,2018-01-06 오후 6:06,73460,184.0,1,네이버 페이,20171231,2018-01-03,2018-01-06
46748,카드,D-20171231-0000026-00,2018-01-03 오후 12:43,2018-01-07 오전 5:38,81620,479.0,1,모바일웹,20171231,2018-01-03,2018-01-07

In [25]:
df2['배송완료일(datetime)']-df2['배송시작일(datetime)'] # timedelta64[ns] : 시간의 간격을 의미하는 데이터 타입 형태
df2['배송시간'] = df2['배송완료일(datetime)']-df2['배송시작일(datetime)']
df2.head()

,결제수단,배송번호,배송시작일,배송완료일,상품구매금액,상품번호,수량,주문경로,주문일,배송시작일(datetime),배송완료일(datetime),배송시간
0,무통장입금,D-20181227-0000648-00,2019-01-07 오전 8:56,2019-01-11 오전 5:32,71450,1077.0,1,PC쇼핑몰,20181227,2019-01-07,2019-01-11,4 days
1,무통장입금,D-20181229-0000119-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,141240,42.0,2,모바일웹,20181229,2019-01-03,2019-01-07,4 days
2,무통장입금,D-20181230-0000100-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,13910,1271.0,1,모바일웹,20181230,2019-01-03,2019-01-07,4 days
3,무통장입금,D-20181231-0000087-00,2019-01-03 오전 9:30,2019-01-07 오전 5:32,81600,1085.0,1,모바일웹,20181231,2019-01-03,2019-01-07,4 days
4,무통장입금,D-20181231-0000108-00,2019-01-07 오전 8:56,2019-01-11 오전 5:32,94710,1106.0,1,모바일웹,20181231,2019-01-07,2019-01-11,4 days

In [22]:
df2['배송시간'].describe()  # 평균, 최대, 최소 값 개수 등 확인

count                        46749
mean     4 days 04:38:57.008278251
std      1 days 04:56:12.144368428
min                0 days 00:00:00
25%                4 days 00:00:00
50%                4 days 00:00:00
75%                4 days 00:00:00
max               47 days 00:00:00
Name: 배송시간, dtype: object

In [26]:
df2['주문일']   # dtype : int64

0        20181227
1        20181229
2        20181230
3        20181231
4        20181231
           ...
46744    20171229
46745    20171229
46746    20171230
46747    20171231
46748    20171231
Name: 주문일, Length: 46749, dtype: int64

In [27]:
pd.to_datetime(df2['주문일'])   # 1970년 1월 1일부터 시작되는 마이크로 초 형태로 인식

0       1970-01-01 00:00:00.020181227
1       1970-01-01 00:00:00.020181229
2       1970-01-01 00:00:00.020181230
3       1970-01-01 00:00:00.020181231
4       1970-01-01 00:00:00.020181231
                     ...
46744   1970-01-01 00:00:00.020171229
46745   1970-01-01 00:00:00.020171229
46746   1970-01-01 00:00:00.020171230
46747   1970-01-01 00:00:00.020171231
46748   1970-01-01 00:00:00.020171231
Name: 주문일, Length: 46749, dtype: datetime64[ns]

In [30]:
df2['주문일']   # 중간에 '-' 삽입

def date_function2(x):
    # return x[0:4]   # 문자형이 아닌 정수형을 슬라이싱으로 가져올수 없음
    result = str(x)
    return  result[0:4] + '-' + result[4:6] + '-' + result[6:8] # 슬라이싱을 이런식으로 붙여 쓸수 있다

df2['주문일'].apply(date_function2) # 문자형
pd.to_datetime(df2['주문일'].apply(date_function2)) # 날짜형

0       2018-12-27
1       2018-12-29
2       2018-12-30
3       2018-12-31
4       2018-12-31
           ...
46744   2017-12-29
46745   2017-12-29
46746   2017-12-30
46747   2017-12-31
46748   2017-12-31
Name: 주문일, Length: 46749, dtype: datetime64[ns]